export const ProofStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED'
};

export const ValidationStatus = {
  VALID: 'VALID',
  INVALID: 'INVALID',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE'
};

export const AuditEventType = {
  PROOF_CREATED: 'PROOF_CREATED',
  PROOF_SHARED: 'PROOF_SHARED',
  PROOF_VIEWED: 'PROOF_VIEWED',
  PROOF_VALIDATED: 'PROOF_VALIDATED',
  PROOF_REVOKED: 'PROOF_REVOKED',
  PROOF_EXPIRED: 'PROOF_EXPIRED'
};
