"""Transaction diagnosis, recovery policy, and synthetic failure scenarios."""

from app.domain.models import FailureCode, RecoveryAction, ScenarioSummary, TransactionDiagnosis, TransactionState, TransactionStep


def step(name: str, status: str, message: str, owner: str, action: str | None = None) -> TransactionStep:
    return TransactionStep(name=name, status=status, message=message, owner=owner, nextAction=action)  # type: ignore[arg-type]


SCENARIOS: dict[str, tuple[ScenarioSummary, TransactionDiagnosis]] = {
    "identity-mismatch": (ScenarioSummary(id="identity-mismatch", title="Identity details do not match", description="The issuer record cannot be matched to the supplied details."), TransactionDiagnosis(transactionId="demo-cbse-2026", documentLabel="Class XII marksheet (demonstration)", trustLabel="Government issued", state=TransactionState.FAILED, overallStatus="action_required", issueCode=FailureCode.IDENTITY_MISMATCH, issuerStatus="available", summary="The issuer responded, but its record could not be matched to the request details.", steps=[step("Account access", "complete", "The official sign-in step was completed.", "Citizen / official service"), step("Identity match", "attention", "The issuer could not match the name, date of birth or document year.", "Issuing organisation", "Check these fields against the issuer record and use its official correction route if needed."), step("Document retrieval", "not_started", "Retrieval starts after the identity record matches.", "Document platform / issuer")], recovery=RecoveryAction(label="Correct the issuer record", type="correct_record", guidance="DigiIn cannot change an official record. Confirm the record with the issuer, then start a new official retrieval attempt."), fallbackAvailable=False, supportReference="DIGIIN-DEMO-IM-2026")),
    "issuer-unavailable": (ScenarioSummary(id="issuer-unavailable", title="Issuer service is unavailable", description="The document issuer cannot currently respond to a lookup."), TransactionDiagnosis(transactionId="demo-issuer-2026", documentLabel="Class XII marksheet (demonstration)", trustLabel="Government issued", state=TransactionState.FAILED, overallStatus="unavailable", issueCode=FailureCode.ISSUER_TIMEOUT, issuerStatus="unavailable", summary="The issuing organisation is not responding to document lookup requests.", steps=[step("Account access", "complete", "The official sign-in step was completed.", "Citizen / official service"), step("Issuer lookup", "blocked", "The issuer service is temporarily unavailable.", "Issuing organisation", "Retry later or use the issuer's official support route if the document is urgent."), step("Document retrieval", "not_started", "Retrieval cannot start until the issuer responds.", "Document platform / issuer")], recovery=RecoveryAction(label="Use an official fallback", type="official_fallback", guidance="Use the issuer's official website or support channel. A production configuration would show an authorised issuer-specific route."), fallbackAvailable=True, supportReference="DIGIIN-DEMO-IU-2026")),
    "callback-failed": (ScenarioSummary(id="callback-failed", title="Requesting portal did not receive confirmation", description="Authorisation succeeded, but the destination portal did not complete handoff."), TransactionDiagnosis(transactionId="demo-callback-2026", documentLabel="Verified marksheet (demonstration)", trustLabel="Government issued", state=TransactionState.FAILED, overallStatus="action_required", issueCode=FailureCode.CALLBACK_FAILED, issuerStatus="available", summary="The document was authorised, but the requesting portal did not confirm receipt.", steps=[step("Account access", "complete", "The official sign-in step was completed.", "Citizen / official service"), step("Document retrieval", "complete", "The issued document was located and authorised.", "Document platform / issuer"), step("Destination handoff", "attention", "The requesting portal did not confirm receipt.", "Requesting service", "Return to the requesting portal and start its official handoff flow once more.")], recovery=RecoveryAction(label="Return to the requesting portal", type="return_to_requester", guidance="The requesting service owns this step. If it repeats, contact its support with the safe reference below."), fallbackAvailable=False, supportReference="DIGIIN-DEMO-CB-2026")),
    "resolved": (ScenarioSummary(id="resolved", title="Document journey completed", description="A complete end-to-end issued-document journey."), TransactionDiagnosis(transactionId="demo-resolved-2026", documentLabel="Driving licence (demonstration)", trustLabel="Government issued", state=TransactionState.COMPLETED, overallStatus="resolved", issueCode=FailureCode.JOURNEY_COMPLETE, issuerStatus="available", summary="The official document was located, verified and received by the requesting service.", steps=[step("Account access", "complete", "The official sign-in step was completed.", "Citizen / official service"), step("Document retrieval", "complete", "The issued document was found and verified.", "Document platform / issuer"), step("Destination handoff", "complete", "The requesting service confirmed receipt.", "Requesting service")], recovery=RecoveryAction(label="Journey complete", type="retry_later", guidance="No recovery action is needed for this demonstration journey."), fallbackAvailable=False, supportReference="DIGIIN-DEMO-OK-2026")),
}


def get_diagnosis(scenario_id: str) -> TransactionDiagnosis | None:
    scenario = SCENARIOS.get(scenario_id)
    return scenario[1] if scenario else None


def list_scenarios() -> list[ScenarioSummary]:
    return [item[0] for item in SCENARIOS.values()]
