export const cn=(...v)=>v.filter(Boolean).join(' ');
export const Button=({label,href,type='button',variant='primary',className='',disabled=false,icon='',id=''})=>href?`<a id="${id}" class="btn btn-${variant} ${className}" href="${href}">${icon?`<span aria-hidden="true">${icon}</span>`:''}${label}</a>`:`<button id="${id}" type="${type}" class="btn btn-${variant} ${className}" ${disabled?'disabled':''}>${icon?`<span aria-hidden="true">${icon}</span>`:''}${label}</button>`;
export const Badge=({label,tone='neutral',icon=''})=>`<span class="badge badge-${tone}">${icon?`<span aria-hidden="true">${icon}</span>`:''}${label}</span>`;
export const Card=({children,className='',id=''})=>`<section id="${id}" class="card ${className}">${children}</section>`;
export const Alert=({title='',message,tone='info',className=''})=>`<div class="alert alert-${tone} ${className}" role="${tone==='error'?'alert':'status'}"><span class="alert-icon" aria-hidden="true">${tone==='success'?'✓':tone==='warning'?'!':tone==='error'?'×':'i'}</span><div>${title?`<strong>${title}</strong>`:''}<div>${message}</div></div></div>`;
export const Field=({id,label,hint='',error='',type='text',placeholder='',value='',required=false,prefix=''})=>`<div class="field"><label for="${id}">${label}${required?' <span aria-hidden="true">*</span>':''}</label>${hint?`<div class="field-hint" id="${id}-hint">${hint}</div>`:''}${prefix?`<div style="display:flex;gap:0.5rem"><span style="display:inline-flex;align-items:center;padding:0 0.75rem;background:#E2E8F0;border:1px solid #CBD5E1;border-radius:6px;font-weight:700;font-size:0.85rem">${prefix}</span>`:''}<input id="${id}" name="${id}" type="${type}" placeholder="${placeholder}" value="${value}" ${required?'required':''} ${error?`aria-invalid="true" aria-describedby="${id}-error"`:hint?`aria-describedby="${id}-hint"`:''}>${prefix?'</div>':''}${error?`<div class="field-error" id="${id}-error" role="alert">${error}</div>`:''}</div>`;
export const Status=({status})=>{const map={verified:['success','✓','Verified'],pending:['warning','◷','Pending'],failed:['error','×','Failed'],retrieving:['info','●','Retrieving'],verifying:['info','●','Verifying']};const [tone,icon,label]=map[status]||['neutral','•',status];return Badge({label,tone,icon})};
export const DocumentCard=({title,issuer,detail,status='verified'})=>Card({className:'document-card',children:`<div style="display:flex;justify-content:space-between;align-items:flex-start"><div><h3 style="font-size:1rem;font-weight:700;margin-bottom:0.25rem">${title}</h3><p style="font-size:0.75rem;color:#475569;margin-bottom:0.5rem">${issuer} • ${detail}</p></div>${Status({status})}</div>`});
export const Stepper=({steps,current=0})=>`<ol style="display:flex;list-style:none;gap:1rem;margin-bottom:1.5rem;padding:0" aria-label="Progress">${steps.map((s,i)=>`<li style="font-size:0.8rem;font-weight:700;color:${i===current?'#0B5D9B':i<current?'#14743F':'#64748B'}">${i<current?'✓':i+1}. ${s}</li>`).join('')}</ol>`;
