import { Button, Badge, Card, Alert, Field, Status, DocumentCard, Stepper } from './components.js';
import { digiLockerService } from './services/digilocker/digilockerService.js';
import { verificationService } from './services/verificationService.js';
import { proofService } from './services/proof/proofService.js';
import { organisationService } from './services/organisation/organisationService.js';
import { requestService } from './services/requests/requestService.js';
import { identityService } from './services/identity/identityService.js';
import { permissionService } from './services/permissions/permissionService.js';
import { securityService } from './services/security/securityService.js';
import { auditService } from './services/audit/auditService.js';
import { apiClientService } from './services/developer/apiClientService.js';
import { webhookService } from './services/developer/webhookService.js';
import { apiContract } from './services/developer/developerMock.js';

const app = document.querySelector('#app');
const state = {
  menu: false,
  lang: 'EN',
  user: null,
  consent: false,
  verification: 'idle',
  request: {
    id: 'VR-82A91',
    organisation: 'ABC University',
    purpose: 'Admission verification',
    documents: [
      { id: 'doc-10', title: 'Class 10 Certificate', issuer: 'CBSE', purpose: 'Eligibility verification' },
      { id: 'doc-12', title: 'Class 12 Certificate', issuer: 'CBSE', purpose: 'Eligibility verification' }
    ],
    expiresInHours: 24
  },
  connection: 'not_connected',
  retrieved: [],
  verificationResult: null,
  verificationProgress: { stage: 'ready', label: 'Ready for verification' },
  proof: null,
  proofHistory: [],
  proofValidation: null,
  organisation: null,
  organisationRequests: [],
  requestStats: { total: 0, verified: 0, pending: 0, expired: 0 },
  requestDraft: { citizenId: '', purpose: '', otherPurpose: '', documents: [], validityHours: 24 }
};

const path = () => location.hash.replace(/^#/, '') || '/';
const go = (p) => { location.hash = p; };
const currentRequest = () => state.request;

const Header = () => `<div class="top"><div class="container top-inner"><span>Government service experience foundation</span><span>Accessible • Secure • Citizen-first</span></div></div><header class="header"><div class="container head"><a class="brand" href="#/" aria-label="DigiIn home"><span class="mark">DI</span><span>DigiIn<small>Digital document verification</small></span></a><nav class="nav" aria-label="Primary"><a href="#/">Home</a><a href="#/how">How it works</a><a href="#/security">Security</a><a href="#/help">Help</a><a href="#/organisation/sign-in">Organisation</a></nav><div class="actions"><button class="btn btn-secondary btn-small" id="lang" type="button" aria-label="Change language">${state.lang === 'EN' ? 'हिन्दी' : 'English'}</button>${state.user ? '<a class="btn btn-primary btn-small" href="#/dashboard">Dashboard</a>' : '<a class="btn btn-primary btn-small" href="#/sign-in">Sign in</a>'}<a class="btn btn-secondary btn-small" href="#/organisation/sign-in">Organisation</a><button class="menu" id="menu" type="button" aria-label="Open menu" aria-expanded="${state.menu}">☰</button></div></div>${state.menu ? `<nav class="mobile-nav" aria-label="Mobile navigation"><a href="#/">Home</a><a href="#/how">How it works</a><a href="#/security">Security</a><a href="#/help">Help</a>${state.user ? '<a href="#/dashboard">Dashboard</a>' : '<a href="#/sign-in">Sign in</a>'}</nav>` : ''}</header>`;

const Footer = () => `<footer class="footer"><div class="container footer-grid"><div><strong>DigiIn</strong><p class="muted">Verify once. Share securely.</p></div><div><strong>Service</strong><a href="#/how">How it works</a><a href="#/security">Security</a><a href="#/help">Help</a></div><div><strong>Information</strong><a href="#/accessibility">Accessibility</a><a href="#/privacy">Privacy</a><a href="#/terms">Terms</a></div></div><div class="container footer-bottom"><small>Prototype foundation • No real documents are processed in demo mode.</small></div></footer>`;

const Page = ({ eyebrow, title, description, children, narrow = false }) => `<main id="main" class="page"><div class="container ${narrow ? 'narrow' : ''}">${eyebrow ? `<span class="eyebrow">${eyebrow}</span>` : ''}<h1>${title}</h1>${description ? `<p class="lead muted">${description}</p>` : ''}${children}</div></main>`;

function Home() { return `<main id="main"><section class="hero"><div class="container hero-grid"><div><span class="eyebrow">Secure document verification</span><h1>Verify once.<br><span>Share securely.</span></h1><p>DigiIn helps citizens use verified digital documents across government and trusted services without repeatedly submitting the same documents.</p><div class="actions hero-actions">${Button({ label: 'Start verification', href: '#/verify/request', icon: '→' })}${Button({ label: 'How DigiIn works', href: '#/how', variant: 'secondary' })}</div><div class="trust-row"><span>✓ Consent-led</span><span>✓ Accessible</span><span>✓ Privacy-first</span></div></div>${Card({ className: 'hero-card', children: `<div class="shield">✓</div><h2>Consent-led by design</h2><p class="muted">You stay in control of what is shared, with whom, and for what purpose.</p><ul class="list"><li>Requesting organisation is clearly identified.</li><li>Only requested documents are shared.</li><li>Every verification has a clear status.</li></ul>` })}</div></section><section class="section"><div class="container"><div class="section-heading"><div><span class="eyebrow">Simple by design</span><h2>A simpler verification journey</h2></div><p class="muted">Designed around the citizen, not the paperwork.</p></div><div class="grid3">${['Connect once', 'Give clear consent', 'Share proof'].map((x, i) => Card({ className: 'feature-card', children: `<div class="icon">0${i + 1}</div><h3>${x}</h3><p class="muted">${['Keep trusted digital documents available in one place.', 'See who needs what and why before anything is shared.', 'Share a verification result instead of repeated document copies.'][i]}</p>` })).join('')}</div></div></section><section class="section section-alt"><div class="container"><span class="eyebrow">The journey</span><h2>How verification works</h2>${Stepper({ steps: ['Request', 'Consent', 'Verify', 'Result'], current: 3 })}</div></section></main>`; }

function SignIn() { return Page({ eyebrow: 'Citizen account', title: 'Sign in to DigiIn', description: 'Use your registered mobile number to continue.', narrow: true, children: `${Alert({ title: 'Demo mode', message: 'Any valid 10-digit mobile number is accepted. No real identity data is processed.', tone: 'info' })}<form id="signin" class="form-card">${Field({ id: 'mobile', label: 'Mobile number', hint: 'Enter the 10-digit number registered with your account.', type: 'tel', placeholder: '10-digit mobile number', required: true })}${Button({ label: 'Continue', type: 'submit', className: 'block' })}<p class="form-footer">By continuing, you agree to the DigiIn <a href="#/terms">terms</a> and <a href="#/privacy">privacy notice</a>.</p></form>` }); }

function Dashboard() { return Page({ eyebrow: 'Citizen account', title: 'Welcome back', description: 'Manage your verified documents and active requests.', children: `<div class="actions"><a class="btn btn-primary" href="#/verify/request">New verification <span aria-hidden="true">→</span></a></div><div class="stats"><div class="stat-card"><strong>12</strong><span>Documents</span></div><div class="stat-card"><strong>9</strong><span>Verified</span></div><div class="stat-card"><strong>2</strong><span>Pending</span></div></div><div class="dashboard-grid">${Card({ children: `<div class="card-heading"><div><span class="eyebrow">Your identity</span><h2>DigiIn ID</h2></div>${Badge({ label: 'Active', tone: 'success', icon: '✓' })}</div><div class="id-card"><small>DigiIn ID</small><strong>DIN-84K2-19Q7</strong><p>Use this ID with authorised services to start a verification request.</p><button class="btn btn-secondary btn-small" id="copy-id" type="button">Copy ID</button></div>` })}${Card({ children: `<div class="card-heading"><div><span class="eyebrow">Activity</span><h2>Recent activity</h2></div></div><ul class="activity"><li><span class="activity-dot success"></span><div><strong>Class 12 verified</strong><small>Today • CBSE</small></div></li><li><span class="activity-dot info"></span><div><strong>University request received</strong><small>Yesterday</small></div></li></ul>` })}</div><section class="documents-section"><div class="section-heading"><div><span class="eyebrow">Document vault</span><h2>Your documents</h2></div></div><div class="document-grid">${DocumentCard({ title: 'Class 12 Certificate', issuer: 'CBSE', detail: 'Issued 15 May 2025', status: 'verified' })}${DocumentCard({ title: 'Class 10 Certificate', issuer: 'CBSE', detail: 'Issued 20 May 2023', status: 'verified' })}${DocumentCard({ title: 'Identity document', issuer: 'Connected source', detail: 'Awaiting verification', status: 'pending' })}</div></section>` }); }

function OrganisationCard() { const r = currentRequest(); return `<div class="requester"><div class="org-mark">AU</div><div><strong>${r.organisation}</strong><span>Verified organisation • ${r.purpose}</span></div><span class="verified-org">✓ Verified</span></div>`; }

function RequestedDocuments() { return `<div class="requested-list">${currentRequest().documents.map((d) => `<div class="requested requested-rich"><div class="document-mini-icon" aria-hidden="true">▤</div><div><strong>${d.title}</strong><small>Issued by ${d.issuer} • ${d.purpose}</small></div><span class="required-label">Required</span></div>`).join('')}</div>`; }

function VerifyRequest() { return Page({ eyebrow: 'Verification request', title: 'Review the request', description: 'Before connecting a trusted document source, understand who is requesting your information and why.', narrow: true, children: `${Stepper({ steps: ['Request', 'Consent', 'Verify', 'Result'], current: 0 })}<div class="form-card request-card">${OrganisationCard()}<div class="request-summary"><div><small>Purpose</small><strong>${currentRequest().purpose}</strong></div><div><small>Request ID</small><strong>${currentRequest().id}</strong></div><div><small>Consent validity</small><strong>${currentRequest().expiresInHours} hours</strong></div></div><h2>Documents requested</h2>${RequestedDocuments()}${Alert({ title: 'You stay in control.', message: 'DigiIn will not request unrelated documents. You can review the exact consent terms before anything is shared.', tone: 'info' })}<div class="actions request-actions"><a class="btn btn-primary" href="#/verify/review">Review and continue <span aria-hidden="true">→</span></a><a class="btn btn-secondary" href="#/dashboard">Cancel</a></div></div>` }); }

function VerifyReview() { return Page({ eyebrow: 'Step 1 of 4 • Review', title: 'Review what will be shared', description: 'This request is limited to the documents and purpose shown below.', narrow: true, children: `${Stepper({ steps: ['Request', 'Consent', 'Verify', 'Result'], current: 0 })}<div class="form-card">${OrganisationCard()}<div class="review-block"><span class="eyebrow">Purpose</span><h2>${currentRequest().purpose}</h2><p class="muted">The organisation will use the verification result only for this stated purpose.</p></div><h2>Requested documents</h2>${RequestedDocuments()}${Alert({ title: 'What will happen next?', message: 'You will connect to DigiLocker, authenticate there, and then return to DigiIn to review and give explicit consent.', tone: 'info' })}<a class="btn btn-primary block" href="#/verify/digilocker">Continue to DigiLocker <span aria-hidden="true">→</span></a><a class="text-action" href="#/verify/request">← Back to request</a></div>` }); }

function DigiLockerConnect() { return Page({ eyebrow: 'Step 2 of 4 • Trusted source', title: 'Connect DigiLocker', description: 'DigiIn needs access to the requested documents from your DigiLocker account.', narrow: true, children: `${Stepper({ steps: ['Request', 'Consent', 'Verify', 'Result'], current: 1 })}<div class="form-card external-card"><div class="external-service-logo">DL</div><h2>Connect to DigiLocker</h2><p class="muted">You will be redirected to DigiLocker to authenticate. DigiIn does not ask for or store your DigiLocker password.</p><div class="security-points"><div>✓ Authentication happens with DigiLocker</div><div>✓ Only this verification request is in scope</div><div>✓ Nothing is shared without your consent</div></div><div id="connection-status" aria-live="polite"></div><button id="connect-digilocker" class="btn btn-primary block" type="button">Continue to DigiLocker <span aria-hidden="true">→</span></button><a class="text-action" href="#/verify/review">← Back to review</a></div>` }); }

function Consent() { return Page({ eyebrow: 'Step 3 of 4 • Consent', title: 'Review and give consent', description: 'Give permission only if the request matches what you intend to verify.', narrow: true, children: `${Stepper({ steps: ['Request', 'Consent', 'Verify', 'Result'], current: 1 })}<div class="form-card consent-card">${OrganisationCard()}<div class="consent-section"><span class="eyebrow">What will be shared</span>${RequestedDocuments()}</div><div class="consent-section"><span class="eyebrow">Why</span><h2>${currentRequest().purpose}</h2><p class="muted">The documents will be checked against their issuing sources to produce a verification result.</p></div>${Alert({ title: 'What will not happen', message: 'Other documents in your DigiLocker account will not be requested as part of this verification.', tone: 'success' })}<div class="consent-expiry"><strong>Consent validity</strong><span>This request expires in ${currentRequest().expiresInHours} hours.</span></div><label class="check-field consent-check"><input id="consent" type="checkbox"><span>I understand what is being requested and consent to this verification.</span></label><button id="give-consent" class="btn btn-primary block" type="button" disabled>Give consent and retrieve documents <span aria-hidden="true">→</span></button><a class="text-action" href="#/verify/digilocker">← Back</a></div>` }); }

function Retrieving() { return Page({ eyebrow: 'Step 3 of 4 • Retrieval', title: 'Retrieving your documents', description: 'We are retrieving only the documents you approved for this request.', narrow: true, children: `${Stepper({ steps: ['Request', 'Consent', 'Verify', 'Result'], current: 2 })}<div class="form-card retrieval-card"><div class="progress-ring" aria-hidden="true">●</div><div id="retrieval-status" aria-live="polite"><h2>Connecting securely…</h2><p class="muted">Please keep this page open.</p></div><ol class="process-list"><li class="active"><span>1</span><div><strong>Permission confirmed</strong><small>Your consent has been recorded.</small></div></li><li id="retrieve-step"><span>2</span><div><strong>Retrieve requested documents</strong><small>Getting the two documents in this request.</small></div></li><li id="prepare-step"><span>3</span><div><strong>Prepare verification</strong><small>Documents will be ready for the verification service.</small></div></li></ol></div>` }); }

function VerifyCheck() { return Page({ eyebrow: 'Step 4 • Verification', title: 'Ready to verify', description: 'Review the final verification scope before DigiIn checks the retrieved documents.', narrow: true, children: `${Stepper({ steps: ['Request', 'Consent', 'Verify', 'Result'], current: 2 })}<div class="form-card">${OrganisationCard()}<div class="review-block"><span class="eyebrow">Purpose</span><h2>${currentRequest().purpose}</h2><p class="muted">The retrieved documents will be checked against trusted verification data.</p></div><h2>Documents</h2>${state.retrieved.map((d) => `<div class="requested requested-rich"><div class="document-mini-icon" aria-hidden="true">▤</div><div><strong>${d.title}</strong><small>${d.issuer} • Ready</small></div>${Status({ status: 'retrieving' })}</div>`).join('')}<button id="begin-verification" class="btn btn-primary block" type="button">Start verification <span aria-hidden="true">→</span></button></div>` }); }

function VerifyProgress() { const p=state.verificationProgress; return Page({ eyebrow: 'Step 4 • Verification', title: 'Verification in progress', description: 'DigiIn is checking each requested document against trusted verification data.', narrow: true, children: `${Stepper({ steps: ['Request', 'Consent', 'Verify', 'Result'], current: 2 })}<div class="form-card retrieval-card"><div class="progress-ring" aria-hidden="true">●</div><div aria-live="polite"><h2>${p.label}</h2><p class="muted">Please keep this page open while verification is completed.</p></div><ol class="process-list verification-process"><li class="${['started','integrity','issuer','details'].includes(p.stage)?'active':''}"><span>1</span><div><strong>Documents received</strong><small>Retrieved with your consent.</small></div></li><li class="${['issuer','details','decision','completed'].includes(p.stage)?'active':''}"><span>2</span><div><strong>Integrity and issuer checks</strong><small>Checking document and issuing authority information.</small></div></li><li class="${['details','decision','completed'].includes(p.stage)?'active':''}"><span>3</span><div><strong>Match document details</strong><small>Comparing required details with trusted records.</small></div></li><li class="${['decision','completed'].includes(p.stage)?'active':''}"><span>4</span><div><strong>Prepare result</strong><small>Generating the verification reference.</small></div></li></ol></div>` }); }

function VerifyDocument({ id }) { const doc=(state.verificationResult?.documents||[]).find(d=>d.id===id); if(!doc) return Info('Document verification details', ['Document not found', 'Return to the verification result to view available documents.']); return Page({ eyebrow: 'Verification detail', title: doc.title, description: 'A transparent view of the checks used for this verification result.', narrow: true, children: `<div class="form-card"><div class="card-heading"><div><span class="eyebrow">${doc.issuer}</span><h2>${doc.title}</h2></div>${Status({ status: doc.status })}</div><div class="verification-checks">${doc.checks.map(c=>`<div class="verification-check"><span class="check-icon">✓</span><div><strong>${c.label}</strong><small>${c.message}</small></div></div>`).join('')}</div><a class="btn btn-primary block" href="#/verify/result">Back to result</a></div>` }); }


function ProofPage({ id }) {
  const proof = state.proof || null;
  if (!proof || proof.proofId !== id) return Page({ eyebrow:'Verification proof', title:'Proof not available', description:'Complete a verification first or open a valid DigiIn proof link.', narrow:true, children:'<a class="btn btn-primary" href="#/verify/result">Return to verification</a>' });
  const valid = proof.status === 'active';
  const statusLabel = valid ? 'Valid' : proof.status === 'expired' ? 'Expired' : 'Revoked';
  const tone = valid ? 'success' : 'warning';
  return Page({ eyebrow:'Digital verification proof', title:'Verification proof', description:'A privacy-minimized proof that can be independently checked without accessing the underlying documents.', narrow:true, children:`<div class="form-card proof-hero"><div class="proof-status">${Badge({label:statusLabel,tone,icon:valid?'✓':'!'})}</div><div><span class="eyebrow">Verification ID</span><div class="proof-id"><strong>${proof.verificationId}</strong></div></div><div class="proof-table"><div class="proof-row"><span>Organisation</span><strong>${proof.organisation}</strong></div><div class="proof-row"><span>Purpose</span><strong>${proof.purpose}</strong></div><div class="proof-row"><span>Documents verified</span><strong>${proof.verifiedDocuments.length}</strong></div><div class="proof-row"><span>Issued</span><strong>${new Date(proof.issuedAt).toLocaleString()}</strong></div><div class="proof-row"><span>Expires</span><strong>${new Date(proof.expiresAt).toLocaleString()}</strong></div></div><h2>Verified documents</h2><div class="verification-list">${proof.verifiedDocuments.map(d=>`<div>${Status({status:'verified'})}<span><strong>${d.title}</strong><small>${d.issuer}</small></span></div>`).join('')}</div>${Alert({title:'Privacy by design',message:'This proof confirms the verification result. It does not expose the citizen’s underlying document files or DigiLocker credentials.',tone:'info'})}<div class="proof-actions">${valid?`<a class="btn btn-primary" href="#/proof/${encodeURIComponent(proof.proofId)}/share">Share proof</a><a class="btn btn-secondary" href="#/proof/${encodeURIComponent(proof.proofId)}/qr">Show QR</a><button id="revoke-proof" class="btn btn-secondary" type="button">Revoke proof</button>`:''}<a class="btn btn-secondary" href="#/dashboard">Dashboard</a></div><p id="proof-msg" class="muted" aria-live="polite"></p></div>` });
}

function ShareProof({ id }) {
  const proof=state.proof;
  if(!proof || proof.proofId!==id) return Info('Proof unavailable',['Proof not found','Return to the verification result and create a new proof.']);
  const url=proofService.getShareUrl(id);
  return Page({eyebrow:'Share verification',title:'Share this verification proof',description:'Share a secure reference that lets an organisation validate the current proof status.',narrow:true,children:`<div class="form-card"><span class="eyebrow">Secure verification link</span><div class="share-box"><input id="share-url" type="text" readonly value="${url}" aria-label="Secure verification link"><button id="copy-share-url" class="btn btn-secondary" type="button">Copy link</button></div><p id="share-url-msg" class="muted" aria-live="polite"></p>${Alert({title:'Only a proof reference is shared',message:'The link does not contain the underlying documents, DigiLocker credentials, or account secrets.',tone:'success'})}<div class="proof-actions"><a class="btn btn-primary" href="#/proof/${encodeURIComponent(id)}/qr">Show QR</a><a class="btn btn-secondary" href="#/proof/${encodeURIComponent(id)}">Back to proof</a></div></div>`});
}

function QRProof({ id }) {
  const proof=state.proof;
  if(!proof || proof.proofId!==id) return Info('QR unavailable',['Proof not found','Return to the proof page.']);
  const cells=Array.from({length:144},(_,i)=>`<span style="opacity:${((i*17+id.length*7)%5===0)?0.12:1}"></span>`).join('');
  return Page({eyebrow:'Share verification',title:'Show QR code',description:'An organisation can scan this reference and independently check whether the proof is currently valid.',narrow:true,children:`<div class="form-card"><div class="qr-panel"><div class="qr-grid" aria-label="QR-style proof reference visual" role="img">${cells}</div><strong>${proof.proofId}</strong><span class="muted-note">Demo QR visual — production will encode a backend verification URL.</span></div><div class="proof-actions"><a class="btn btn-primary" href="#/verify-proof?id=${encodeURIComponent(id)}">Open verifier</a><a class="btn btn-secondary" href="#/proof/${encodeURIComponent(id)}">Back to proof</a></div></div>`});
}

function VerifyProof() {
  const query=new URLSearchParams(location.hash.split('?')[1]||'');
  const id=query.get('id')||'';
  return Page({eyebrow:'Organisation verification',title:'Verify a DigiIn proof',description:'Enter a proof reference to independently check its current status.',narrow:true,children:`<div class="form-card"><label for="proof-id">Verification proof ID</label><div class="field-hint">Example: DIN-PRF-51Q8-X2</div><input id="proof-id" type="text" value="${id}" placeholder="Enter proof ID" autocomplete="off"><button id="validate-proof" class="btn btn-primary block" type="button">Verify proof</button><div id="proof-validation" class="validation-result" aria-live="polite"></div><p class="muted-note">A DigiIn proof confirms a verification result. It does not provide access to the citizen’s document vault.</p></div>`});
}

function ProofValidationResult() {
  const result=state.proofValidation;
  if(!result) return Info('Proof validation',['No validation result yet','Enter a DigiIn proof ID to continue.']);
  const p=result.proof;
  const config={active:['success','✓','Verification confirmed'],expired:['warning','!','Verification proof expired'],revoked:['warning','!','Verification proof revoked'],invalid:['error','×','Verification could not be confirmed']}[result.status]||['error','×','Verification unavailable'];
  return Page({eyebrow:'Organisation verification',title:config[2],description:result.message||'DigiIn has checked the current status of this proof.',narrow:true,children:`<div class="form-card validation-result"><div class="validation-state"><span class="state-icon">${config[1]}</span><div>${Badge({label:config[2],tone:config[0],icon:config[1]})}<p class="muted">${result.status==='invalid'?'This proof is not recognised by DigiIn.':result.status==='expired'?'This proof is no longer active.':result.status==='revoked'?'This proof was previously valid but has been revoked.':'The proof is currently active and matches a DigiIn verification record.'}</p></div></div>${p?`<div class="proof-table"><div class="proof-row"><span>Organisation</span><strong>${p.organisation}</strong></div><div class="proof-row"><span>Purpose</span><strong>${p.purpose}</strong></div><div class="proof-row"><span>Documents verified</span><strong>${p.verifiedDocuments.length}</strong></div><div class="proof-row"><span>Verification ID</span><strong>${p.verificationId}</strong></div><div class="proof-row"><span>Issued</span><strong>${new Date(p.issuedAt).toLocaleString()}</strong></div><div class="proof-row"><span>Valid until</span><strong>${new Date(p.expiresAt).toLocaleString()}</strong></div></div><h2>Verified documents</h2><div class="verification-list">${p.verifiedDocuments.map(d=>`<div>${Status({status:'verified'})}<span><strong>${d.title}</strong><small>${d.issuer}</small></span></div>`).join('')}</div>`:''}${Alert({title:'Privacy-minimized verification',message:'Only the information necessary to confirm the proof is shown here. Underlying documents are not exposed.',tone:'info'})}<a class="btn btn-secondary block" href="#/verify-proof">Verify another proof</a></div>`});
}

function VerificationResult() { const r=state.verificationResult; if(!r) return Page({ eyebrow:'Verification', title:'No result yet', description:'Complete verification first.', narrow:true, children:'<a class="btn btn-primary" href="#/verify/documents">Return to documents</a>' }); const tone=r.status==='verified'?'success':r.status==='partial'?'warning':'error'; const icon=r.status==='verified'?'✓':r.status==='partial'?'!':'×'; const label=r.status==='verified'?'Verified':r.status==='partial'?'Partially verified':'Verification failed'; return Page({ eyebrow:'Step 4 of 4 • Verification result', title:'Verification result', description:'Review the overall decision and the result for each requested document.', narrow:true, children:`<div class="result-card"><div class="result-icon result-${r.status}">${icon}</div>${Badge({label,tone,icon})}<div class="result-summary"><strong>${r.verified} of ${r.total}</strong><span>documents verified</span></div><div class="verification-list">${r.documents.map(d=>`<div><span>${Status({status:d.status})}</span><span><strong>${d.title}</strong><small>${d.issuer}</small></span><a class="link-button" href="#/verify/document/${d.id}">View details →</a></div>`).join('')}</div><div class="verification-id"><small>Verification ID</small><strong>${r.id}</strong><button id="copy-verification" class="btn btn-secondary btn-small" type="button">Copy ID</button><p id="verification-copy-msg" class="muted" aria-live="polite"></p></div><div class="verification-meta"><span>Purpose</span><strong>${currentRequest().purpose}</strong></div><div class="actions centered"><button id="create-proof" class="btn btn-primary" type="button">Create verification proof</button><a class="btn btn-secondary" href="#/dashboard">Go to dashboard</a><a class="btn btn-secondary" href="#/verify/request">Start another</a></div><p id="proof-create-msg" class="muted" aria-live="polite"></p></div>` }); }

function DocumentsReady() { return Page({ eyebrow: 'Step 3 of 4 • Documents ready', title: 'Documents retrieved', description: `${state.retrieved.length} requested documents are ready for verification.`, narrow: true, children: `${Stepper({ steps: ['Request', 'Consent', 'Verify', 'Result'], current: 2 })}<div class="form-card"><div class="ready-summary"><span class="ready-icon">✓</span><div><h2>Ready for verification</h2><p class="muted">Only the documents approved in your consent are available to the verification step.</p></div></div><div class="document-grid single">${state.retrieved.map((d) => DocumentCard({ title: d.title, issuer: d.issuer, detail: 'Retrieved from DigiLocker • Ready for verification', status: 'retrieving' })).join('')}</div>${Alert({ title: 'Privacy note', message: 'DigiIn is using these documents only for the verification request you approved.', tone: 'info' })}<button id="start-verification" class="btn btn-primary block" type="button">Start verification <span aria-hidden="true">→</span></button></div>` }); }

function Result() { return Page({ eyebrow: 'Step 4 of 4 • Verification result', title: 'Verification complete', description: '2 of 2 requested documents were successfully verified.', narrow: true, children: `<div class="result-card"><div class="result-icon">✓</div>${Badge({ label: 'Verified', tone: 'success', icon: '✓' })}<div class="result-summary"><strong>2 of 2</strong><span>documents verified</span></div><div class="verification-list"><div>${Status({ status: 'verified' })}<span>Class 10 Certificate</span><small>CBSE</small></div><div>${Status({ status: 'verified' })}<span>Class 12 Certificate</span><small>CBSE</small></div></div><div class="verification-id"><small>Verification ID</small><strong>DIN-VRF-82A91</strong><button id="share" class="btn btn-secondary btn-small" type="button">Copy ID</button></div><p id="sharemsg" class="muted" aria-live="polite"></p><div class="actions centered"><a class="btn btn-primary" href="#/dashboard">Go to dashboard</a><a class="btn btn-secondary" href="#/verify/request">Start another</a></div></div>` }); }


const OrgNav = ({active=''}) => `<aside class="org-sidebar">${Card({children:`<div class="org-title" style="margin-bottom:1rem"><div class="org-avatar">AU</div><div><strong>ABC University</strong><small class="muted">Verified organisation</small></div></div><nav class="org-nav" aria-label="Organisation navigation"><a class="${active==='dashboard'?'active':''}" href="#/organisation/dashboard">Dashboard</a><a class="${active==='requests'?'active':''}" href="#/organisation/requests">Requests</a><a class="${active==='new'?'active':''}" href="#/organisation/requests/new">+ Create request</a><a class="${active==='verify'?'active':''}" href="#/organisation/verify-proof">Verify proof</a><a class="${active==='history'?'active':''}" href="#/organisation/history">History</a><a class="${active==='profile'?'active':''}" href="#/organisation/profile">Profile</a><a class="${active==='developer'?'active':''}" href="#/organisation/developer">Developer</a><a href="#/">Citizen site</a></nav>`})}</aside>`;
const OrgPage = ({active,title,description,children}) => Page({eyebrow:'Organisation portal',title,description,children:`<div class="org-shell">${OrgNav({active})}<div class="org-content">${children}</div></div>`});
const statusLabel = (s) => ({completed:'Verified',awaiting_consent:'Awaiting consent',verifying:'Verifying',sent:'Sent',expired:'Expired',cancelled:'Cancelled',failed:'Failed'})[s] || s;
const statusTone = (s) => s==='completed'?'success':['expired','cancelled','failed'].includes(s)?'error':'warning';

function OrganisationSignIn(){ return Page({eyebrow:'Organisation access',title:'Sign in to the organisation portal',description:'Authorised organisations use this workspace to request and verify citizen information.',narrow:true,children:`<div class="form-card"><div class="org-login-mark">AU</div>${Alert({title:'Demo mode',message:'Use any organisation ID and email. No real credentials are stored.',tone:'info'})}<form id="org-signin">${Field({id:'org-id',label:'Organisation ID',value:'ORG-84K2-19Q7',required:true})}${Field({id:'org-email',label:'Email',type:'email',value:'verification@abcuniversity.example',required:true})}${Field({id:'org-password',label:'Password',type:'password',value:'demo-password',required:true})}${Button({label:'Sign in',type:'submit',className:'block'})}</form></div>`}); }

function ensureOrg(){ if(!state.organisation) { go('/organisation/sign-in'); return false; } return true; }

async function loadOrg(){ state.organisation=state.organisation||await organisationService.getOrganisation(); state.organisationRequests=await requestService.listRequests(); state.requestStats=await requestService.stats(); }

function OrganisationDashboard(){ if(!state.organisation) { setTimeout(async()=>{await loadOrg();render()},0); return Page({eyebrow:'Organisation portal',title:'Loading workspace…',description:'Preparing your organisation dashboard.',children:''}); } const recent=state.organisationRequests.slice(0,3); return OrgPage({active:'dashboard',title:'Organisation dashboard',description:'Create verification requests and monitor verification activity.',children:`<div class="org-header"><div><div class="org-title"><div class="org-avatar">AU</div><div><strong>${state.organisation.name}</strong><small class="muted">${state.organisation.id} • Verified organisation</small></div></div></div><div class="actions"><a class="btn btn-primary" href="#/organisation/requests/new">Create verification request →</a><a class="btn btn-secondary" href="#/organisation/verify-proof">Verify proof</a></div></div><div class="org-stat-grid"><div class="org-stat"><strong>${state.requestStats.total}</strong><span>Total requests</span></div><div class="org-stat"><strong>${state.requestStats.verified}</strong><span>Verified</span></div><div class="org-stat"><strong>${state.requestStats.pending}</strong><span>Pending</span></div><div class="org-stat"><strong>${state.requestStats.expired}</strong><span>Expired</span></div></div>${Card({children:`<div class="section-heading"><div><span class="eyebrow">Recent activity</span><h2>Verification requests</h2></div><a href="#/organisation/requests">View all</a></div>${recent.map(r=>`<div class="mini-row"><div><strong>${r.id}</strong><small class="muted">${r.purpose} • ${r.citizenId}</small></div><span class="status-chip ${r.status}">${statusLabel(r.status)}</span></div>`).join('')}`})}`}); }

function OrganisationRequests(){ if(!ensureOrg()) return ''; const rows=state.organisationRequests; return OrgPage({active:'requests',title:'Verification requests',description:'Track requests, consent and verification outcomes.',children:`<div class="filter-row"><select id="request-filter" aria-label="Filter requests"><option value="all">All statuses</option><option value="awaiting_consent">Awaiting consent</option><option value="completed">Verified</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select><a class="btn btn-primary btn-small" href="#/organisation/requests/new">Create request</a></div><div id="request-list">${Card({children:`<div class="request-table-wrap"><table class="request-table"><thead><tr><th>Request</th><th>Citizen</th><th>Purpose</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr data-status="${r.status}"><td><strong>${r.id}</strong></td><td>${r.citizenId}</td><td>${r.purpose}</td><td><span class="status-chip ${r.status}">${statusLabel(r.status)}</span></td><td>${new Date(r.createdAt).toLocaleDateString('en-IN')}</td><td><a href="#/organisation/requests/${r.id}">View</a></td></tr>`).join('')}</tbody></table></div>`})}</div>`}); }

function CreateRequest(){ if(!ensureOrg()) return ''; const d=state.requestDraft; const docs=[['class10','Class 10 Certificate','Confirm school qualification'],['class12','Class 12 Certificate','Confirm senior secondary qualification'],['degree','Degree Certificate','Confirm higher education qualification'],['identity','Identity Document','Confirm identity']]; return OrgPage({active:'new',title:'Create verification request',description:'Request only the information needed for a defined purpose.',children:`${Stepper({steps:['Citizen','Purpose','Documents','Review'],current:0})}<form id="create-request" class="form-card"><div class="request-step"><div class="request-step-num">1</div><div><h2>Citizen</h2>${Field({id:'citizen-id',label:'Citizen DigiIn ID',hint:'A DigiIn ID identifies an account. It does not grant access to documents.',placeholder:'DIN-7K4P-92M8',value:d.citizenId,required:true})}</div></div><div class="request-step"><div class="request-step-num">2</div><div><h2>Purpose</h2><div class="field"><label for="purpose">Verification purpose <span aria-hidden="true">*</span></label><select id="purpose" required style="width:100%;min-height:48px;padding:.7rem;border:1px solid var(--color-border);border-radius:var(--radius-md)"><option value="">Select purpose</option>${['Admission','Employment','Scholarship','Government service','Financial service','Identity verification','Other'].map(x=>`<option ${d.purpose===x?'selected':''}>${x}</option>`).join('')}</select></div><div id="other-purpose-wrap" style="display:${d.purpose==='Other'?'block':'none'}">${Field({id:'other-purpose',label:'Describe the purpose',value:d.otherPurpose,placeholder:'Describe why verification is required'})}</div></div></div><div class="request-step"><div class="request-step-num">3</div><div><h2>Documents requested</h2><p class="muted">Select only what is necessary.</p>${docs.map(([id,title,reason])=>`<label class="doc-option"><input type="checkbox" name="document" value="${id}" ${d.documents.includes(id)?'checked':''}><span><strong>${title}</strong><small>${reason}</small></span></label>`).join('')}<div class="field" style="margin-top:1rem"><label for="validity">Request validity</label><select id="validity" style="width:100%;min-height:48px;padding:.7rem;border:1px solid var(--color-border);border-radius:var(--radius-md)">${[[1,'1 hour'],[6,'6 hours'],[24,'24 hours'],[72,'3 days'],[168,'7 days']].map(([v,l])=>`<option value="${v}" ${d.validityHours===v?'selected':''}>${l}</option>`).join('')}</select></div></div></div><div class="actions" style="margin-top:1.25rem"><a class="btn btn-secondary" href="#/organisation/dashboard">Cancel</a><button class="btn btn-primary" type="submit">Review request →</button></div></form>`}); }

function ReviewRequest(){ if(!ensureOrg()) return ''; const d=state.requestDraft; const names={class10:'Class 10 Certificate',class12:'Class 12 Certificate',degree:'Degree Certificate',identity:'Identity Document'}; return OrgPage({active:'new',title:'Review verification request',description:'Check the scope before creating the request.',children:`${Stepper({steps:['Citizen','Purpose','Documents','Review'],current:3})}<div class="form-card request-review"><div class="review-row"><span>Citizen</span><strong>${d.citizenId}</strong></div><div class="review-row"><span>Purpose</span><strong>${d.purpose==='Other'?d.otherPurpose:d.purpose}</strong></div><div class="review-row"><span>Documents</span><strong>${d.documents.map(x=>names[x]).join(', ')||'None selected'}</strong></div><div class="review-row"><span>Validity</span><strong>${d.validityHours} hours</strong></div>${Alert({message:'The citizen must explicitly consent before any requested documents can be retrieved.',tone:'info'})}<div class="actions"><a class="btn btn-secondary" href="#/organisation/requests/new">Back</a><button class="btn btn-primary" id="confirm-create" type="button">Create request</button></div></div>`}); }

async function createRequestAndGo(){ const d=state.requestDraft; const r=await requestService.createRequest({citizenId:d.citizenId,purpose:d.purpose==='Other'?d.otherPurpose:d.purpose,documents:d.documents,validityHours:d.validityHours}); state.organisationRequests=await requestService.listRequests(); state.requestStats=await requestService.stats(); go(`/organisation/requests/${r.id}`); }

function OrganisationRequestDetail({id}){ if(!ensureOrg()) return ''; const r=state.organisationRequests.find(x=>x.id===id); if(!r) return OrgPage({active:'requests',title:'Request not found',description:'The requested verification request does not exist.',children:Alert({message:'Check the request ID and try again.',tone:'error'})}); return OrgPage({active:'requests',title:`Verification request ${r.id}`,description:'Review request scope, consent and verification status.',children:`<div class="actions" style="margin-bottom:1rem"><a class="btn btn-secondary" href="#/organisation/requests">← Back to requests</a>${['awaiting_consent','sent'].includes(r.status)?'<button class="btn btn-secondary" id="cancel-request">Cancel request</button>':''}</div>${Card({children:`<div class="request-summary"><div><small>Citizen</small><strong>${r.citizenId}</strong></div><div><small>Purpose</small><strong>${r.purpose}</strong></div><div><small>Status</small><strong>${statusLabel(r.status)}</strong></div></div><div class="review-block"><h2>Requested documents</h2><div class="requested-list">${r.documents.map(x=>`<div class="requested"><strong>${({class10:'Class 10 Certificate',class12:'Class 12 Certificate',degree:'Degree Certificate',identity:'Identity Document'})[x]||x}</strong><small>Requested for ${r.purpose}</small></div>`).join('')}</div></div><div class="review-block"><h2>Consent</h2>${r.status==='completed'||r.status==='verifying'?Alert({message:'Consent granted for the requested scope.',tone:'success'}):r.status==='awaiting_consent'?Alert({message:'Waiting for the citizen to review and grant consent.',tone:'info'}):Alert({message:'No active consent is available for this request.',tone:'warning'})}</div><div class="review-block"><h2>Verification</h2>${r.status==='completed'?`<div class="verification-list"><div>${Status({status:'verified'})}<span>Class 10 Certificate</span><small>Verified</small></div><div>${Status({status:'verified'})}<span>Class 12 Certificate</span><small>Verified</small></div></div><p class="muted">Verification ID: <strong>DIN-VRF-82A91</strong></p><a class="btn btn-primary btn-small" href="#/proof/DEMO">View verification proof</a>`:Alert({message:'The verification result will appear here after consent, retrieval and verification are complete.',tone:'info'})}</div>`})}`}); }

function OrganisationVerifyProof(){ if(!ensureOrg()) return ''; return OrgPage({active:'verify',title:'Verify DigiIn proof',description:'Confirm whether a shared verification proof is currently valid.',children:`${Card({children:`<form id="org-proof-form">${Field({id:'org-proof-id',label:'Verification proof ID',hint:'Enter the proof reference shared by the citizen.',placeholder:'DIN-PRF-51Q8-X2',required:true})}${Button({label:'Verify proof',type:'submit',className:'block'})}</form><p class="muted-note">A proof check returns only the verification result and its validity. It does not open the citizen's document vault.</p>`})}`}); }
function OrganisationHistory(){ if(!ensureOrg()) return ''; return OrgPage({active:'history',title:'Verification history',description:'A chronological view of organisation verification activity.',children:Card({children:`<ul class="activity">${state.organisationRequests.map(r=>`<li><span class="activity-dot ${r.status==='completed'?'success':'info'}"></span><div><strong>${r.id} • ${statusLabel(r.status)}</strong><small>${r.purpose} • ${new Date(r.createdAt).toLocaleString('en-IN')}</small></div></li>`).join('')}</ul>`})}); }
function OrganisationProfile(){ if(!ensureOrg()) return ''; const o=state.organisation; return OrgPage({active:'profile',title:'Organisation profile',description:'Identity and verification details for this organisation account.',children:Card({children:`<div class="org-title"><div class="org-avatar">AU</div><div><h2 style="margin:0">${o.name}</h2><small class="muted">${o.id}</small></div></div><div class="review-block"><div class="review-row"><span>Status</span><strong>${Badge({label:'Verified organisation',tone:'success',icon:'✓'})}</strong></div><div class="review-row"><span>Type</span><strong>${o.type}</strong></div><div class="review-row"><span>Contact</span><strong>${o.email}</strong></div></div>`})}); }
function OrganisationProofResult(){ return Page({eyebrow:'Organisation portal',title:'Proof verification result',description:'The result below is based on the DigiIn proof registry.',narrow:true,children:state.proofValidation?Card({children:`<div class="validation-result">${Alert({title:state.proofValidation.status==='active'?'Verification is valid':state.proofValidation.status==='expired'?'Verification proof expired':state.proofValidation.status==='revoked'?'Verification proof revoked':'Verification could not be confirmed',message:state.proofValidation.status==='active'?'DigiIn confirmed this verification proof as active.':state.proofValidation.message||'This proof is no longer active.',tone:state.proofValidation.status==='active'?'success':state.proofValidation.status==='invalid'?'error':'warning'})}${state.proofValidation.proof?`<div class="review-block"><div class="review-row"><span>Organisation</span><strong>${state.proofValidation.proof.organisation}</strong></div><div class="review-row"><span>Purpose</span><strong>${state.proofValidation.proof.purpose}</strong></div><div class="review-row"><span>Documents verified</span><strong>${state.proofValidation.proof.verifiedDocuments.length}</strong></div><div class="review-row"><span>Valid until</span><strong>${new Date(state.proofValidation.proof.expiresAt).toLocaleString('en-IN')}</strong></div></div>`:''}<a class="btn btn-secondary" href="#/organisation/verify-proof">Verify another proof</a></div>`}):Alert({message:'No validation result is available.',tone:'warning'})}); }

const Info = (title, text, eyebrow = 'Information') => Page({ eyebrow, title, description: text[1], narrow: true, children: Card({ children: `<h2>${text[0]}</h2><p class="muted">${text[2] || 'This information is part of the DigiIn foundation build.'}</p>` }) });
function IdentityPage(){return Page({eyebrow:'Account identity',title:'Your DigiIn identity',description:'Your DigiIn ID identifies your account. It is not a credential and does not grant access to your documents.',narrow:true,children:Card({children:`<div class="id-card"><small>DigiIn ID</small><strong>DIN-84K2-19Q7</strong><p>Account status: <b>Active</b></p><p>Identity status: <b>✓ Verified</b></p><button class="btn btn-secondary btn-small" id="copy-digin-id">Copy DigiIn ID</button></div><div class="review-block"><div class="review-row"><span>Created</span><strong>23 Aug 2026</strong></div><div class="review-row"><span>Security rule</span><strong>Never use the ID as a password</strong></div></div>`})});}
function IdentityDetails(){return Page({eyebrow:'Identity details',title:'DigiIn account identity',description:'A minimal identity record designed for safe referencing across authorised services.',narrow:true,children:Card({children:`<div class="review-block"><div class="review-row"><span>DigiIn ID</span><strong>DIN-84K2-19Q7</strong></div><div class="review-row"><span>Account status</span><strong>${Badge({label:'Active',tone:'success',icon:'✓'})}</strong></div><div class="review-row"><span>Identity status</span><strong>${Badge({label:'Verified',tone:'success',icon:'✓'})}</strong></div><div class="review-row"><span>Created</span><strong>23 Aug 2026</strong></div></div>${Alert({message:'The DigiIn ID identifies the account only. Verification requests still require explicit scope and consent.',tone:'info'})}`})});}
function Privacy(){return Page({eyebrow:'Privacy centre',title:'Your data, your control',description:'Review permissions, connected organisations and sharing activity.',children:`<div class="grid3"><a class="card feature-card" href="#/privacy/permissions"><h2>Permissions</h2><p class="muted">See what each organisation can verify and when access expires.</p></a><a class="card feature-card" href="#/privacy/organisations"><h2>Connected organisations</h2><p class="muted">See organisations that have interacted with your DigiIn account.</p></a><a class="card feature-card" href="#/security/activity"><h2>Activity</h2><p class="muted">Review recent security and verification events.</p></a></div>`});}
async function PermissionsPage(){const ps=await permissionService.list();return Page({eyebrow:'Privacy centre',title:'Permissions',description:'Every permission is purpose-bound, scoped and time-limited.',children:ps.map(p=>Card({children:`<div class="card-heading"><div><span class="eyebrow">${p.organisation}</span><h2>${p.purpose}</h2></div>${Badge({label:p.status==='granted'?'Active':p.status,tone:p.status==='granted'?'success':'warning',icon:p.status==='granted'?'✓':'!'})}</div><div class="review-block"><div class="review-row"><span>Documents</span><strong>${p.scope.join(', ')}</strong></div><div class="review-row"><span>Granted</span><strong>${new Date(p.grantedAt).toLocaleString('en-IN')}</strong></div><div class="review-row"><span>Expires</span><strong>${new Date(p.expiresAt).toLocaleString('en-IN')}</strong></div></div>${p.status==='granted'?`<button class="btn btn-secondary revoke-permission" data-id="${p.id}">Revoke permission</button>`:''}`)}).join('')||Alert({message:'No permissions found.',tone:'info'})});}
async function ConnectedOrganisations(){const ps=await permissionService.list();return Page({eyebrow:'Privacy centre',title:'Connected organisations',description:'A clear view of organisations associated with your verification activity.',children:ps.map(p=>Card({children:`<div class="org-title"><div class="org-avatar">AU</div><div><h2 style="margin:0">${p.organisation}</h2><small>${p.organisationId}</small></div></div><div class="review-block"><div class="review-row"><span>Trust status</span><strong>${Badge({label:'Verified',tone:'success',icon:'✓'})}</strong></div><div class="review-row"><span>Active permissions</span><strong>${p.status==='granted'?1:0}</strong></div><div class="review-row"><span>Purpose</span><strong>${p.purpose}</strong></div></div>`)}).join('')});}
async function Security(){const ss=await securityService.sessions();return Page({eyebrow:'Security centre',title:'Account security',description:'Manage sessions and review security controls.',children:`<div class="stats"><div class="stat-card"><strong>✓</strong><span>Account protected</span></div><div class="stat-card"><strong>${ss.length}</strong><span>Active sessions</span></div><div class="stat-card"><strong>1</strong><span>Active permission</span></div></div><div class="actions"><a class="btn btn-secondary" href="#/security/sessions">Manage sessions</a><a class="btn btn-secondary" href="#/security/activity">View activity</a></div>`});}
async function Sessions(){const ss=await securityService.sessions();return Page({eyebrow:'Security centre',title:'Active sessions',description:'Sign out sessions you no longer recognise or need.',children:ss.map(s=>Card({children:`<div class="card-heading"><div><h2>${s.device}</h2><p class="muted">${s.platform}</p></div>${s.current?Badge({label:'Current session',tone:'success',icon:'✓'}):Badge({label:'Active',tone:'neutral'})}</div><div class="review-row"><span>Last active</span><strong>${s.lastActive}</strong></div>${!s.current?`<button class="btn btn-secondary signout-session" data-id="${s.id}">Sign out</button>`:''}`})).join('')});}
async function Activity(){const ev=await auditService.list();return Page({eyebrow:'Security centre',title:'Security & verification activity',description:'A unified activity timeline across requests, permissions, verification and proofs.',children:Card({children:`<ul class="activity">${ev.map(e=>`<li><span class="activity-dot success"></span><div><strong>${e.type.replaceAll('_',' ')}</strong><small>${e.resource} • ${e.time}</small></div></li>`).join('')}</ul>`})});}
function OrganisationIdentity(){return OrgPage({active:'profile',title:'Organisation identity',description:'Identity and trust information for this organisation.',children:Card({children:`<div class="org-title"><div class="org-avatar">AU</div><div><h2 style="margin:0">ABC University</h2><small>ORG-84K2-19Q7</small></div></div><div class="review-block"><div class="review-row"><span>Trust status</span><strong>${Badge({label:'Verified organisation',tone:'success',icon:'✓'})}</strong></div><div class="review-row"><span>Account status</span><strong>Active</strong></div><div class="review-row"><span>Type</span><strong>Educational institution</strong></div></div>${Alert({message:'Verified organisation status does not by itself grant access to citizen documents.',tone:'info'})}`})});}
async function Developer(){if(!ensureOrg())return '';return OrgPage({active:'developer',title:'Developer portal',description:'Manage API clients, webhooks and integration documentation.',children:`<div class="stats"><div class="stat-card"><strong>v1</strong><span>API version</span></div><div class="stat-card"><strong>128</strong><span>Requests today</span></div><div class="stat-card"><strong>99.2%</strong><span>Success rate</span></div></div><div class="grid3"><a class="card feature-card" href="#/organisation/developer/credentials"><h2>API credentials</h2><p class="muted">Create and revoke scoped API clients.</p></a><a class="card feature-card" href="#/organisation/developer/webhooks"><h2>Webhooks</h2><p class="muted">Configure verification lifecycle events.</p></a><a class="card feature-card" href="#/organisation/developer/docs"><h2>API documentation</h2><p class="muted">Explore the DigiIn API v1 contract.</p></a></div><div class="actions"><a class="btn btn-primary" href="#/organisation/developer/console">Open API console</a></div>`});}
async function Credentials(){if(!ensureOrg())return '';const cs=await apiClientService.list();return OrgPage({active:'developer',title:'API credentials',description:'Use least-privilege clients for system integrations.',children:`${cs.map(c=>Card({children:`<div class="card-heading"><div><span class="eyebrow">${c.name}</span><h2>${c.clientId}</h2></div>${Badge({label:c.status,tone:c.status==='active'?'success':'warning',icon:c.status==='active'?'✓':'!'})}</div><p class="muted">Scopes: ${c.scopes.join(', ')}</p><div class="review-row"><span>Created</span><strong>${c.createdAt}</strong></div>${c.status==='active'?`<button class="btn btn-secondary revoke-api" data-id="${c.id}">Revoke client</button>`:''}`})).join('')}<form id="api-client-form" class="form-card"><h2>Create API client</h2>${Field({id:'client-name',label:'Client name',placeholder:'Admissions Integration',required:true})}<fieldset class="checkbox-group"><legend>Scopes</legend>${['verification:create','verification:read','proof:validate'].map(x=>`<label><input type="checkbox" name="scope" value="${x}" checked> ${x}</label>`).join('')}</fieldset>${Button({label:'Create client',type:'submit'})}<p class="muted-note">A generated secret is displayed once only in demo mode.</p></form>`});}
async function Webhooks(){if(!ensureOrg())return '';const hs=await webhookService.list();return OrgPage({active:'developer',title:'Webhooks',description:'Receive lifecycle notifications from DigiIn.',children:`${hs.map(h=>Card({children:`<div class="card-heading"><div><h2>${h.url}</h2><p class="muted">${h.events.join(' • ')}</p></div>${Badge({label:h.status,tone:h.status==='active'?'success':'warning',icon:h.status==='active'?'✓':'!'})}</div><div class="review-row"><span>Last delivery</span><strong>${h.lastDeliveryAt}</strong></div>${h.status==='active'?`<button class="btn btn-secondary disable-webhook" data-id="${h.id}">Disable</button>`:''}`})).join('')}<form id="webhook-form" class="form-card"><h2>Add webhook</h2>${Field({id:'webhook-url',label:'Endpoint URL',placeholder:'https://example.org/digiin/webhook',required:true})}<fieldset class="checkbox-group"><legend>Events</legend>${['verification.created','verification.completed','proof.created'].map(x=>`<label><input type="checkbox" name="event" value="${x}" checked> ${x}</label>`).join('')}</fieldset>${Button({label:'Add webhook',type:'submit'})}</form>`});}
function DeveloperDocs(){if(!ensureOrg())return '';return OrgPage({active:'developer',title:'DigiIn API v1',description:'Frontend contract documentation for future backend integration.',children:Card({children:`${apiContract.endpoints.map(e=>`<div class="review-block"><div class="card-heading"><strong>${e.method} ${e.path}</strong>${Badge({label:e.scope,tone:'neutral'})}</div><p class="muted">${e.description}</p></div>`).join('')}${Alert({message:'Prototype documentation only. Production authentication, rate limits and server-side validation will be enforced by the DigiIn API.',tone:'info'})}`})});}
function DeveloperConsole(){if(!ensureOrg())return '';return OrgPage({active:'developer',title:'API console',description:'Simulate a DigiIn API request without contacting a production service.',children:Card({children:`<form id="api-console"><div class="review-block"><div class="review-row"><span>Endpoint</span><strong>POST /v1/verification-requests</strong></div>${Field({id:'console-citizen',label:'Citizen DigiIn ID',value:'DIN-84K2-19Q7',required:true})}</div>${Button({label:'Send request',type:'submit'})}</form><div id="console-result" style="margin-top:1rem"></div>`})});}


function render() {
  const p = path();
  let c;
  if (p === '/') c = Home();
  else if (p === '/sign-in') c = SignIn();
  else if (p === '/dashboard') c = Dashboard();
  else if (p === '/account/identity') c = IdentityPage();
  else if (p === '/account/identity/details') c = IdentityDetails();
  else if (p === '/privacy') c = Privacy();
  else if (p === '/privacy/permissions') { c = await PermissionsPage(); }
  else if (p === '/privacy/organisations') { c = await ConnectedOrganisations(); }
  else if (p === '/security') { c = await Security(); }
  else if (p === '/security/sessions') { c = await Sessions(); }
  else if (p === '/security/activity') { c = await Activity(); }
  else if (p === '/verify' || p === '/verify/request') c = VerifyRequest();
  else if (p === '/verify/review') c = VerifyReview();
  else if (p === '/verify/digilocker') c = DigiLockerConnect();
  else if (p === '/verify/consent') c = Consent();
  else if (p === '/verify/retrieving') c = Retrieving();
  else if (p === '/verify/documents') c = DocumentsReady();
  else if (p === '/verify/check') c = VerifyCheck();
  else if (p === '/verify/progress') c = VerifyProgress();
  else if (p.startsWith('/verify/document/')) c = VerifyDocument({ id: p.split('/').pop() });
  else if (p === '/verify/result') c = VerificationResult();
  else if (p.startsWith('/proof/') && p.endsWith('/share')) c = ShareProof({ id: decodeURIComponent(p.split('/')[2]) });
  else if (p.startsWith('/proof/') && p.endsWith('/qr')) c = QRProof({ id: decodeURIComponent(p.split('/')[2]) });
  else if (p.startsWith('/proof/')) c = ProofPage({ id: decodeURIComponent(p.split('/')[2]) });
  else if (p === '/verify-proof') c = VerifyProof();
  else if (p === '/verify-proof/result') c = ProofValidationResult();
  else if (p === '/organisation/sign-in') c = OrganisationSignIn();
  else if (p === '/organisation/dashboard') { if (!state.organisation) { setTimeout(async()=>{ await loadOrg(); render(); },0); c = OrganisationSignIn(); } else c = OrganisationDashboard(); }
  else if (p === '/organisation/requests') c = OrganisationRequests();
  else if (p === '/organisation/requests/new') c = CreateRequest();
  else if (p === '/organisation/requests/review') c = ReviewRequest();
  else if (p.startsWith('/organisation/requests/')) c = OrganisationRequestDetail({ id: p.split('/').pop() });
  else if (p === '/organisation/verify-proof') c = OrganisationVerifyProof();
  else if (p === '/organisation/verify-proof/result') c = OrganisationProofResult();
  else if (p === '/organisation/history') c = OrganisationHistory();
  else if (p === '/organisation/identity') c = OrganisationIdentity();
  else if (p === '/organisation/developer') { c = await Developer(); }
  else if (p === '/organisation/developer/credentials') { c = await Credentials(); }
  else if (p === '/organisation/developer/webhooks') { c = await Webhooks(); }
  else if (p === '/organisation/developer/docs') c = DeveloperDocs();
  else if (p === '/organisation/developer/console') c = DeveloperConsole();
  else if (p === '/organisation/profile') c = OrganisationProfile();
  else if (p === '/result') c = Result();
  else if (p === '/how') c = Info('How DigiIn works', ['A consent-first verification journey', 'An organisation requests only the documents it needs. You review the purpose, connect your trusted source, and approve the request. DigiIn then produces a verification result.']);
  else if (p === '/security') c = Info('Security & privacy', ['Built around least-data sharing', 'The interface makes the requesting organisation, purpose, requested documents, consent state and verification result visible.']);
  else if (p === '/help') c = Info('Help', ['Need help?', 'This foundation uses simulated verification. Production integrations will provide real service status and recovery actions.']);
  else if (p === '/accessibility') c = Info('Accessibility', ['Accessible by default', 'Keyboard navigation, visible focus, semantic landmarks, live status regions, responsive layouts and reduced-motion support are built into the foundation.']);
  else if (p === '/terms') c = Info('Terms of service', ['Hackathon foundation', 'This build contains demonstration content only. Production legal terms will be added before deployment.']);
  else c = Info('Page not found', ['The page does not exist', 'Return to the DigiIn home page.']);
  app.innerHTML = '<a class="skip" href="#main">Skip to main content</a>' + Header() + c + Footer();
  bind();
  if (p === '/verify/retrieving') setTimeout(startRetrieval, 0);
}

function bind() {
  document.querySelector('#menu')?.addEventListener('click', () => { state.menu = !state.menu; render(); });
  document.querySelector('#lang')?.addEventListener('click', () => { state.lang = state.lang === 'EN' ? 'HI' : 'EN'; render(); });
  document.querySelector('#signin')?.addEventListener('submit', (e) => { e.preventDefault(); state.user = { mobile: document.querySelector('#mobile').value }; go('/dashboard'); });
  document.querySelector('#copy-id')?.addEventListener('click', async (e) => { try { await navigator.clipboard.writeText('DIN-84K2-19Q7'); e.currentTarget.textContent = 'Copied ✓'; } catch { e.currentTarget.textContent = 'DIN-84K2-19Q7'; } });

  const connect = document.querySelector('#connect-digilocker');
  connect?.addEventListener('click', async () => {
    const status = document.querySelector('#connection-status');
    connect.disabled = true;
    connect.textContent = 'Connecting securely…';
    state.connection = 'connecting';
    status.innerHTML = Alert({ message: 'Opening DigiLocker authentication…', tone: 'info' });
    try {
      await digiLockerService.connect();
      state.connection = 'authenticating';
      status.innerHTML = Alert({ message: 'DigiLocker authentication complete in demo mode.', tone: 'success' });
      connect.textContent = 'Continue to consent →';
      connect.disabled = false;
      connect.onclick = () => go('/verify/consent');
    } catch {
      state.connection = 'failed';
      connect.disabled = false;
      connect.textContent = 'Try again';
      status.innerHTML = Alert({ title: 'We could not connect to DigiLocker', message: 'No documents were shared. Try again to continue.', tone: 'error' });
    }
  });

  const consent = document.querySelector('#consent');
  const giveConsent = document.querySelector('#give-consent');
  consent?.addEventListener('change', () => { state.consent = consent.checked; giveConsent.disabled = !consent.checked; });
  giveConsent?.addEventListener('click', async () => {
    if (!state.consent) return;
    giveConsent.disabled = true;
    giveConsent.textContent = 'Recording consent…';
    await digiLockerService.getConsentRequest(currentRequest().id);
    go('/verify/retrieving');
  });

  document.querySelector('#start-verification')?.addEventListener('click', () => go('/verify/check'));
  document.querySelector('#begin-verification')?.addEventListener('click', async () => { state.verificationProgress = { stage: 'started', label: 'Starting verification…' }; go('/verify/progress'); const result = await verificationService.verify(state.retrieved, (progress) => { state.verificationProgress = progress; }); state.verificationResult = result; go('/verify/result'); });
  document.querySelector('#copy-verification')?.addEventListener('click', async (e) => { const msg=document.querySelector('#verification-copy-msg'); try { await navigator.clipboard.writeText(state.verificationResult.id); e.currentTarget.textContent='Copied ✓'; msg.textContent='Verification ID copied. Share it only with the authorised organisation.'; } catch { msg.textContent=`Verification ID: ${state.verificationResult.id}`; } });
  document.querySelector('#create-proof')?.addEventListener('click', async (e) => { const msg=document.querySelector('#proof-create-msg'); e.currentTarget.disabled=true; e.currentTarget.textContent='Creating proof…'; state.proof=await proofService.createProof(state.verificationResult,currentRequest()); state.proofHistory=await proofService.history(); go(`/proof/${encodeURIComponent(state.proof.proofId)}`); });
  document.querySelector('#copy-share-url')?.addEventListener('click', async (e)=>{ const input=document.querySelector('#share-url'); const msg=document.querySelector('#share-url-msg'); try { await navigator.clipboard.writeText(input.value); e.currentTarget.textContent='Copied ✓'; msg.textContent='Secure verification link copied.'; } catch { msg.textContent=input.value; }});
  document.querySelector('#revoke-proof')?.addEventListener('click', async (e)=>{ if(!state.proof) return; if(!confirm('Revoke this verification proof? It will no longer validate as active.')) return; e.currentTarget.disabled=true; state.proof=await proofService.revokeProof(state.proof.proofId); state.proofHistory=await proofService.history(); render(); });
  document.querySelector('#validate-proof')?.addEventListener('click', async ()=>{ const input=document.querySelector('#proof-id'); const box=document.querySelector('#proof-validation'); const id=input.value.trim(); if(!id){ box.innerHTML=Alert({title:'Enter a proof ID',message:'Provide the DigiIn proof reference to continue.',tone:'error'}); return; } box.innerHTML=Alert({message:'Checking proof with DigiIn…',tone:'info'}); state.proofValidation=await proofService.validateProof(id); go('/verify-proof/result'); });
  document.querySelector('#share')?.addEventListener('click', async (e) => { const m = document.querySelector('#sharemsg'); try { await navigator.clipboard.writeText('DigiIn Verification ID: DIN-VRF-82A91'); e.currentTarget.textContent = 'Copied ✓'; m.textContent = 'Verification ID copied. Share it only with the authorised organisation.'; } catch { m.textContent = 'Verification ID: DIN-VRF-82A91'; } });
  document.querySelector('#org-signin')?.addEventListener('submit', async (e)=>{ e.preventDefault(); const btn=e.currentTarget.querySelector('button[type="submit"]'); btn.disabled=true; btn.textContent='Signing in…'; state.organisation=await organisationService.signIn(document.querySelector('#org-id').value); await loadOrg(); go('/organisation/dashboard'); });
  document.querySelector('#purpose')?.addEventListener('change',(e)=>{ document.querySelector('#other-purpose-wrap').style.display=e.target.value==='Other'?'block':'none'; });
  document.querySelector('#create-request')?.addEventListener('submit',(e)=>{ e.preventDefault(); state.requestDraft.citizenId=document.querySelector('#citizen-id').value.trim(); state.requestDraft.purpose=document.querySelector('#purpose').value; state.requestDraft.otherPurpose=document.querySelector('#other-purpose')?.value.trim()||''; state.requestDraft.documents=[...document.querySelectorAll('input[name="document"]:checked')].map(x=>x.value); state.requestDraft.validityHours=Number(document.querySelector('#validity').value); if(!state.requestDraft.documents.length){ alert('Select at least one document.'); return; } if(state.requestDraft.purpose==='Other'&&!state.requestDraft.otherPurpose){ alert('Describe the verification purpose.'); return; } go('/organisation/requests/review'); });
  document.querySelector('#confirm-create')?.addEventListener('click',async(e)=>{ e.currentTarget.disabled=true; e.currentTarget.textContent='Creating request…'; await createRequestAndGo(); });
  document.querySelector('#cancel-request')?.addEventListener('click',async(e)=>{ const id=path().split('/').pop(); if(!confirm('Cancel this verification request?')) return; e.currentTarget.disabled=true; await requestService.cancelRequest(id); await loadOrg(); render(); });
  document.querySelector('#request-filter')?.addEventListener('change',(e)=>{ document.querySelectorAll('#request-list tbody tr').forEach(row=>{ row.hidden=e.target.value!=='all'&&row.dataset.status!==e.target.value; }); });
  document.querySelector('#org-proof-form')?.addEventListener('submit',async(e)=>{ e.preventDefault(); const id=document.querySelector('#org-proof-id').value.trim(); if(!id)return; state.proofValidation=await proofService.validateProof(id); go('/organisation/verify-proof/result'); });
  document.querySelector('#copy-digin-id')?.addEventListener('click', async (e)=>{try{await navigator.clipboard.writeText('DIN-84K2-19Q7');e.currentTarget.textContent='Copied ✓';}catch{e.currentTarget.textContent='DIN-84K2-19Q7';}});
  document.querySelectorAll('.revoke-permission').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Revoke this permission?'))return;await permissionService.revoke(b.dataset.id);render();}));
  document.querySelectorAll('.signout-session').forEach(b=>b.addEventListener('click',async()=>{await securityService.signOut(b.dataset.id);b.textContent='Signed out ✓';b.disabled=true;}));
  document.querySelectorAll('.revoke-api').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Revoke this API client?'))return;await apiClientService.revoke(b.dataset.id);render();}));
  document.querySelector('#api-client-form')?.addEventListener('submit',async(e)=>{e.preventDefault();const name=document.querySelector('#client-name').value.trim();const scopes=[...document.querySelectorAll('input[name="scope"]:checked')].map(x=>x.value);const c=await apiClientService.create(name,scopes);alert(`Client created. Secret (shown once): ${c.secret}`);render();});
  document.querySelectorAll('.disable-webhook').forEach(b=>b.addEventListener('click',async()=>{await webhookService.disable(b.dataset.id);render();}));
  document.querySelector('#webhook-form')?.addEventListener('submit',async(e)=>{e.preventDefault();const url=document.querySelector('#webhook-url').value.trim();const events=[...document.querySelectorAll('input[name="event"]:checked')].map(x=>x.value);await webhookService.create(url,events);render();});
  document.querySelector('#api-console')?.addEventListener('submit',(e)=>{e.preventDefault();document.querySelector('#console-result').innerHTML=Alert({title:'201 Created',message:'{ "requestId": "VR-92K7A", "status": "awaiting_consent" }',tone:'success'});});

}

async function startRetrieval() {
  const status = document.querySelector('#retrieval-status');
  const retrieveStep = document.querySelector('#retrieve-step');
  const prepareStep = document.querySelector('#prepare-step');
  if (!status) return;
  await new Promise((r) => setTimeout(r, 700));
  status.innerHTML = '<h2>Retrieving requested documents…</h2><p class="muted">DigiLocker is returning only the documents in your consent.</p>';
  retrieveStep?.classList.add('active');
  state.retrieved = await digiLockerService.getDocuments();
  await new Promise((r) => setTimeout(r, 500));
  status.innerHTML = '<h2>Documents ready</h2><p class="muted">Your consented documents are ready for verification.</p>';
  prepareStep?.classList.add('active');
  setTimeout(() => go('/verify/documents'), 700);
}

window.addEventListener('hashchange', () => { state.menu = false; render(); });
render();
